language: cpp

compiler:
  - clang
  - gcc

pre-install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt541
 - sudo apt-get update -qq

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt541
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54base
 - /opt/qt54/bin/qt54-env.sh

script:
 - /opt/qt54/bin/qmake -v
 - /opt/qt54/bin/qmake -project
 - /opt/qt54/bin/qmake Tunnel/Tunnel.pro
 - make
