language: cpp

install:
 - sudo add-apt-repository --yes ppa:beineri/opt-qt54
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54default qt54tools 

script:
 - qmake -project
 - qmake Tunnel/Tunnel.pro
 - make
