language: cpp

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt541
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54base qt54tools 
 - export QMAKE=/opt/qt54/bin/qmake

script:
 - qmake -v
 - qmake -project
 - qmake Tunnel/Tunnel.pro
 - make
