language: cpp
dist: trusty
compiler:
  - clang
  - gcc

pre-install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
 - sudo apt-get update -qq

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt591-trusty
 - sudo apt-get update -qq
 - sudo apt-get install -y qt59base
 - /opt/qt59/bin/qt59-env.sh

script:
 - /opt/qt59/bin/qmake -v
 - /opt/qt59/bin/qmake -project
 - /opt/qt59/bin/qmake Tunnel/Tunnel.pro
 - make
