language: cpp

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt541
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54base qt54tools 
 - sudo dpkg -L qt54 base

script:
 - qmake -qt=qt5 -v
 - qmake -qt=qt5 -project
 - qmake -qt=qt5 Tunnel/Tunnel.pro
 - make
