language: cpp

install:
 - sudo add-apt-repository -y ppa:beineri/opt-qt541
 - sudo apt-get update -qq
 - sudo apt-get install -y qt54base qt54tools qt54creator qt54qbs wk54 qt54graphicaleffects qt54-meta
 - /opt/qt54/bin/qt54-env.sh

script:
 - /opt/qt54/bin/qmake -v
 - /opt/qt54/bin/qmake -project
 - /opt/qt54/bin/qmake Tunnel/Tunnel.pro
 - make
